// Generated by scripts/generate_profiles.py from profiles/builds.json. Do not edit by hand.
#pragma once

#include <cstdint>
#include <string_view>

namespace native_game {

enum class BuildId { unknown, cd_10012, cd_10019, dvd_20000, cd_10020 };

struct Profile {
    std::uint32_t application;
    std::uint32_t draw_slot;
    std::uint32_t draw_list;
    std::uint32_t talk_list;
    std::uint32_t history_list;
    std::uint32_t current_input;
    std::uint32_t main_menu;
    std::uint32_t script_root;
    std::uint32_t script_control;
    std::uint32_t input_graphic;
    std::uint32_t text;
    std::uint32_t movie;
    std::uint32_t action_movie;
    std::uint32_t emotion;
    std::uint32_t picture;
    std::uint32_t viewport;
    std::uint32_t lookup;
    std::uint32_t release;
    std::uint32_t picture_bounds;
    std::uint32_t activate;
    std::uint32_t remove;
    std::uint32_t pause;
    std::uint32_t restore_preferences;
    std::uint32_t restore_view;
    std::uint32_t session_active;
    std::uint32_t scene_active;
    std::uint32_t menu_used;
    std::uint32_t children;
    std::uint32_t control_rectangle;
    std::uint32_t string_create;
    std::uint32_t string_destroy;
    std::uint32_t save_state;
    std::uint32_t save_file;
    std::uint32_t load_file;
    std::uint32_t pending_load;
    std::uint32_t choice_viewport;
    std::uint32_t text_draw;
    std::uint32_t text_out;
    std::uint32_t string_resource;
    std::uint32_t asset_reference;
    std::uint32_t credit_group;
    std::uint32_t credit_update;
    std::uint32_t credit_draw;
    std::uint32_t credit_invalidate;
    std::uint32_t credit_outer;
    std::uint32_t canvas_invalidate;
    std::uint32_t canvas_transfer_call;
    std::uint32_t canvas_transfer;
    std::uint32_t credit_position;
    std::uint32_t canvas;
    std::uint32_t select_inventory;
    std::uint32_t set_inventory_action;
    std::uint32_t owned_inventory_item;
    std::uint32_t registered_gun_action;
    std::uint32_t inventory_action_variable;
    std::uint32_t selected_inventory;
    std::uint32_t queue_mouse_move;
};

struct Build {
    BuildId id;
    std::string_view label;
    std::string_view edition;
    std::string_view sha256;
    const Profile* profile;
};

inline constexpr Profile profile_cd_10012{
    .application = 0x2b2ecc,
    .draw_slot = 0x25e844,
    .draw_list = 0x17070,
    .talk_list = 0x2bd018,
    .history_list = 0x2bd168,
    .current_input = 0x40c60,
    .main_menu = 0x256718,
    .script_root = 0x253a30,
    .script_control = 0x257510,
    .input_graphic = 0x25a290,
    .text = 0x25c1e0,
    .movie = 0x258d20,
    .action_movie = 0x254020,
    .emotion = 0x2545e0,
    .picture = 0x25cd10,
    .viewport = 0x2c11e8,
    .lookup = 0x41ed0,
    .release = 0x2b790,
    .picture_bounds = 0x1e500,
    .activate = 0x40a40,
    .remove = 0x32d80,
    .pause = 0x6c9b0,
    .restore_preferences = 0x52b20,
    .restore_view = 0x97210,
    .session_active = 0x2b1988,
    .scene_active = 0x2b198c,
    .menu_used = 0x2b1984,
    .children = 0x800,
    .control_rectangle = 0x198,
    .string_create = 0x7c460,
    .string_destroy = 0x95f0,
    .save_state = 0xef220,
    .save_file = 0x1173a0,
    .load_file = 0x1177e0,
    .pending_load = 0x2b19ac,
    .choice_viewport = 0x98,
    .text_draw = 0x25670,
    .text_out = 0x1650c0,
    .string_resource = 0x30d50,
    .asset_reference = 0x263f40,
    .credit_group = 0x25c5c0,
    .credit_update = 0x5e40,
    .credit_draw = 0x5c00,
    .credit_invalidate = 0x2c430,
    .credit_outer = 0x259808,
    .canvas_invalidate = 0x2c400,
    .canvas_transfer_call = 0x944a,
    .canvas_transfer = 0xcee0,
    .credit_position = 0xc0,
    .canvas = 0x7d0,
    .select_inventory = 0xb0710,
    .set_inventory_action = 0xe1e80,
    .owned_inventory_item = 0x253f60,
    .registered_gun_action = 0x2b193c,
    .inventory_action_variable = 0x2b897c,
    .selected_inventory = 0x2b8974,
    .queue_mouse_move = 0x4bd00,
};

inline constexpr Profile profile_cd_10019{
    .application = 0x2b5ef4,
    .draw_slot = 0x260d4c,
    .draw_list = 0x16e20,
    .talk_list = 0x2c0180,
    .history_list = 0x2c02d0,
    .current_input = 0x40700,
    .main_menu = 0x2587a0,
    .script_root = 0x255db8,
    .script_control = 0x2595a8,
    .input_graphic = 0x25c9f0,
    .text = 0x25e978,
    .movie = 0x25b058,
    .action_movie = 0x256038,
    .emotion = 0x256618,
    .picture = 0x25f4a8,
    .viewport = 0x2c4388,
    .lookup = 0x41970,
    .release = 0x2b530,
    .picture_bounds = 0x1e350,
    .activate = 0x404e0,
    .remove = 0x32780,
    .pause = 0x6c080,
    .restore_preferences = 0x523a0,
    .restore_view = 0x96960,
    .session_active = 0x2b49ac,
    .scene_active = 0x2b49b0,
    .menu_used = 0x2b49a8,
    .children = 0x804,
    .control_rectangle = 0x19c,
    .string_create = 0x7baa0,
    .string_destroy = 0x93e0,
    .save_state = 0xf1200,
    .save_file = 0x119960,
    .load_file = 0x119da0,
    .pending_load = 0x2b49d0,
    .choice_viewport = 0x9c,
    .text_draw = 0x254a0,
    .text_out = 0x1680f0,
    .string_resource = 0x30760,
    .asset_reference = 0x2666d0,
    .credit_group = 0x25ed58,
    .credit_update = 0x5c40,
    .credit_draw = 0x5a00,
    .credit_invalidate = 0x2c1d0,
    .credit_outer = 0x25bb58,
    .canvas_invalidate = 0x2c1a0,
    .canvas_transfer_call = 0x923a,
    .canvas_transfer = 0xccd0,
    .credit_position = 0xc4,
    .canvas = 0x7d4,
    .select_inventory = 0xb02c0,
    .set_inventory_action = 0xe3d00,
    .owned_inventory_item = 0x255f78,
    .registered_gun_action = 0x2b496c,
    .inventory_action_variable = 0x2bb97c,
    .selected_inventory = 0x2bb974,
    .queue_mouse_move = 0x4b720,
};

inline constexpr Profile profile_dvd_20000{
    .application = 0x2b6fec,
    .draw_slot = 0x25feac,
    .draw_list = 0x16e20,
    .talk_list = 0x2c0270,
    .history_list = 0x2c03c0,
    .current_input = 0x407c0,
    .main_menu = 0x25d8c0,
    .script_root = 0x25b848,
    .script_control = 0x25d830,
    .input_graphic = 0x25eae8,
    .text = 0x25f928,
    .movie = 0x25d270,
    .action_movie = 0x25dee8,
    .emotion = 0x258310,
    .picture = 0x25f5a0,
    .viewport = 0x2c10e8,
    .lookup = 0x41a30,
    .release = 0x2b610,
    .picture_bounds = 0x1e350,
    .activate = 0x405a0,
    .remove = 0x32850,
    .pause = 0x6c0b0,
    .restore_preferences = 0x52460,
    .restore_view = 0x96730,
    .session_active = 0x2b6b10,
    .scene_active = 0x2b6b14,
    .menu_used = 0x2b6b0c,
    .children = 0x804,
    .control_rectangle = 0x19c,
    .string_create = 0x7bb20,
    .string_destroy = 0x93e0,
    .save_state = 0x106ee0,
    .save_file = 0xcd380,
    .load_file = 0xcd7c0,
    .pending_load = 0x2b6614,
    .choice_viewport = 0x9c,
    .text_draw = 0x25580,
    .text_out = 0x146aa0,
    .string_resource = 0x30830,
    .asset_reference = 0x266328,
    .credit_group = 0x25f268,
    .credit_update = 0x5c40,
    .credit_draw = 0x5a00,
    .credit_invalidate = 0x2c2b0,
    .credit_outer = 0x258280,
    .canvas_invalidate = 0x2c280,
    .canvas_transfer_call = 0x923a,
    .canvas_transfer = 0xccd0,
    .credit_position = 0xc4,
    .canvas = 0x7d4,
    .select_inventory = 0xcb190,
    .set_inventory_action = 0x118fd0,
    .owned_inventory_item = 0x259e58,
    .registered_gun_action = 0x2b6334,
    .inventory_action_variable = 0x2bf764,
    .selected_inventory = 0x2bf75c,
    .queue_mouse_move = 0x4b7e0,
};

inline constexpr Profile profile_cd_10020{
    .application = 0x2b6f04,
    .draw_slot = 0x2620fc,
    .draw_list = 0x16e60,
    .talk_list = 0x2c11e0,
    .history_list = 0x2c1330,
    .current_input = 0x40800,
    .main_menu = 0x259798,
    .script_root = 0x256ee0,
    .script_control = 0x25a5a0,
    .input_graphic = 0x25d9e8,
    .text = 0x25f978,
    .movie = 0x25c050,
    .action_movie = 0x257030,
    .emotion = 0x257610,
    .picture = 0x2604a8,
    .viewport = 0x2c53e8,
    .lookup = 0x41a70,
    .release = 0x2b630,
    .picture_bounds = 0x1e390,
    .activate = 0x405e0,
    .remove = 0x32880,
    .pause = 0x6c1d0,
    .restore_preferences = 0x524a0,
    .restore_view = 0x96ae0,
    .session_active = 0x2b59b4,
    .scene_active = 0x2b59b8,
    .menu_used = 0x2b59b0,
    .children = 0x804,
    .control_rectangle = 0x19c,
    .string_create = 0x7bc00,
    .string_destroy = 0x93e0,
    .save_state = 0xf15b0,
    .save_file = 0x119d90,
    .load_file = 0x11a1d0,
    .pending_load = 0x2b59d8,
    .choice_viewport = 0x9c,
    .text_draw = 0x25530,
    .text_out = 0x168650,
    .string_resource = 0x30850,
    .asset_reference = 0x2676d8,
    .credit_group = 0x25fd58,
    .credit_update = 0x5c40,
    .credit_draw = 0x5a00,
    .credit_invalidate = 0x2c2d0,
    .credit_outer = 0x25cb50,
    .canvas_invalidate = 0x2c2a0,
    .canvas_transfer_call = 0x923a,
    .canvas_transfer = 0xccf0,
    .credit_position = 0xc4,
    .canvas = 0x7d4,
    .select_inventory = 0xb04d0,
    .set_inventory_action = 0xe40f0,
    .owned_inventory_item = 0x256f70,
    .registered_gun_action = 0x2b5974,
    .inventory_action_variable = 0x2bc99c,
    .selected_inventory = 0x2bc994,
    .queue_mouse_move = 0x4b810,
};

inline constexpr Build build_cd_10012{
    BuildId::cd_10012, "CD 1.00.12", "CD",
    "eae65c27f0c026530e363ebc3483a150c002e831e88ae6e04d3c2f3d4da859ce", &profile_cd_10012};
inline constexpr Build build_cd_10019{
    BuildId::cd_10019, "CD 1.00.19", "CD",
    "d1cfec26c69c03a41d3a0e81783a11b7892bc6846f6326b306f99f2ed534e1d6", &profile_cd_10019};
inline constexpr Build build_dvd_20000{
    BuildId::dvd_20000, "DVD 2.05.00", "DVD",
    "1c7385b15bc11f6ff46b5a30ca383441df96be5be1c1dec31eae650f2243a2ad", &profile_dvd_20000};
inline constexpr Build build_cd_10020{
    BuildId::cd_10020, "CD 1.00.20", "CD",
    "0f8b654cb78f6ae66d62bb173fae79614255ad46cdc25827bbaa98d7d0d79899", &profile_cd_10020};

inline constexpr const Build* build_for_hash(std::string_view sha256) {
    if (sha256 == build_cd_10012.sha256) {
        return &build_cd_10012;
    }
    if (sha256 == build_cd_10019.sha256) {
        return &build_cd_10019;
    }
    if (sha256 == build_dvd_20000.sha256) {
        return &build_dvd_20000;
    }
    if (sha256 == build_cd_10020.sha256) {
        return &build_cd_10020;
    }
    return nullptr;
}

inline constexpr const Profile* profile_for_build(BuildId id) {
    switch (id) {
        case BuildId::cd_10012:
            return build_cd_10012.profile;
        case BuildId::cd_10019:
            return build_cd_10019.profile;
        case BuildId::dvd_20000:
            return build_dvd_20000.profile;
        case BuildId::cd_10020:
            return build_cd_10020.profile;
        default:
            return nullptr;
    }
}

}
