"""Validate native build profiles and emit the C++ address table."""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
FIELDS = (
    "application draw_slot draw_list talk_list history_list current_input main_menu "
    "script_root script_control input_graphic text movie action_movie emotion picture "
    "viewport lookup release picture_bounds activate remove pause restore_preferences "
    "restore_view session_active scene_active menu_used children control_rectangle "
    "string_create string_destroy save_state save_file load_file pending_load choice_viewport "
    "text_draw text_out string_resource asset_reference "
    "credit_group credit_update credit_draw credit_invalidate credit_outer canvas_invalidate "
    "canvas_transfer_call canvas_transfer credit_position canvas "
    "select_inventory set_inventory_action owned_inventory_item registered_gun_action "
    "inventory_action_variable selected_inventory queue_mouse_move"
).split()
OFFSETS = {"children", "control_rectangle", "choice_viewport", "credit_position", "canvas"}
BUILD_IDS = ("cd_10012", "cd_10019", "dvd_20000", "cd_10020")


def validate(data):
    if set(data) != {"schema", "builds"} or data["schema"] != 1:
        raise ValueError("Invalid profile schema")
    builds = data["builds"]
    if not isinstance(builds, list) or [b.get("id") for b in builds] != list(BUILD_IDS):
        raise ValueError("Build IDs must appear once in the defined order")
    hashes = set()
    for build in builds:
        if set(build) != {"id", "label", "edition", "sha256", "rvas", "offsets"}:
            raise ValueError("Invalid build keys")
        digest = build["sha256"]
        if not isinstance(digest, str) or len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest) or digest in hashes:
            raise ValueError("Invalid or duplicate SHA-256")
        hashes.add(digest)
        if not isinstance(build["label"], str) or not re.fullmatch(r"[A-Za-z0-9 ._-]+", build["label"]):
            raise ValueError("Invalid build label")
        if build["edition"] not in ("CD", "DVD"):
            raise ValueError("Invalid edition")
        if (build["rvas"] is None) != (build["offsets"] is None):
            raise ValueError("Partial profile")
        if build["rvas"] is None:
            continue
        if set(build["rvas"]) != set(FIELDS) - OFFSETS or set(build["offsets"]) != OFFSETS:
            raise ValueError("Missing or extra address fields")
        for group in ("rvas", "offsets"):
            for name, value in build[group].items():
                if not isinstance(value, int) or isinstance(value, bool) or value <= 0 or value >= 0x100000000:
                    raise ValueError(f"Invalid {group} value: {name}")
                if group == "offsets" and value >= 0x10000:
                    raise ValueError(f"Layout offset too large: {name}")
    if builds[0]["rvas"] is None or builds[2]["rvas"] is None:
        raise ValueError("Existing supported builds need profiles")


def validate_functions(catalog, profiles):
    if set(catalog) != {"schema", "functions"} or catalog["schema"] != 1:
        raise ValueError("Invalid function catalog schema")
    rows = catalog["functions"]
    if not isinstance(rows, list) or not rows or any(not isinstance(row, dict) for row in rows):
        raise ValueError("Invalid function entries")
    available = set.intersection(*(set(build["rvas"]) for build in profiles["builds"]
                                   if build["rvas"] is not None))
    fields = [row.get("field") for row in rows]
    if any(not isinstance(field, str) for field in fields) or len(set(fields)) != len(fields) or any(field not in available for field in fields):
        raise ValueError("Function fields must be unique profile RVAs")
    for row in rows:
        if set(row) != {"field", "role", "abi"} or row["field"] not in available:
            raise ValueError("Invalid function entry")
        if not isinstance(row["role"], str) or not re.fullmatch(r"[A-Za-z0-9 *-]{1,80}", row["role"]):
            raise ValueError("Invalid function role")
        if not isinstance(row["abi"], str) or not re.fullmatch(r"__[a-z]+\([A-Za-z0-9_, *]+\)", row["abi"]):
            raise ValueError("Invalid function ABI")


def render(data):
    lines = [
        "// Generated by scripts/generate_profiles.py from profiles/builds.json. Do not edit by hand.",
        "#pragma once", "", "#include <cstdint>", "#include <string_view>", "",
        "namespace native_game {", "",
        "enum class BuildId { unknown, " + ", ".join(BUILD_IDS) + " };", "",
        "struct Profile {",
    ]
    lines.extend(f"    std::uint32_t {name};" for name in FIELDS)
    lines += ["};", "", "struct Build {", "    BuildId id;", "    std::string_view label;", "    std::string_view edition;", "    std::string_view sha256;", "    const Profile* profile;", "};", ""]
    for build in data["builds"]:
        if build["rvas"] is None:
            continue
        lines.append(f"inline constexpr Profile profile_{build['id']}{{")
        for name in FIELDS:
            group = "offsets" if name in OFFSETS else "rvas"
            lines.append(f"    .{name} = 0x{build[group][name]:x},")
        lines += ["};", ""]
    for build in data["builds"]:
        profile = f"&profile_{build['id']}" if build["rvas"] is not None else "nullptr"
        lines += [f"inline constexpr Build build_{build['id']}{{",
                  f"    BuildId::{build['id']}, \"{build['label']}\", \"{build['edition']}\",",
                  f"    \"{build['sha256']}\", {profile}}};"]
    lines += ["", "inline constexpr const Build* build_for_hash(std::string_view sha256) {"]
    for build in data["builds"]:
        name = "build_" + build["id"]
        lines += [f"    if (sha256 == {name}.sha256) {{", f"        return &{name};", "    }"]
    lines += ["    return nullptr;", "}", "",
              "inline constexpr const Profile* profile_for_build(BuildId id) {", "    switch (id) {"]
    for build in data["builds"]:
        lines += [f"        case BuildId::{build['id']}:", f"            return build_{build['id']}.profile;"]
    lines += ["        default:", "            return nullptr;", "    }", "}", "", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads((ROOT / "profiles/builds.json").read_text(encoding="utf-8"))
    validate(data)
    functions = json.loads((ROOT / "profiles/functions.json").read_text(encoding="utf-8"))
    validate_functions(functions, data)
    target = ROOT / "profiles/generated.h"
    generated = render(data)
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != generated:
            raise SystemExit("profiles/generated.h is stale. Run src/game/scripts/generate_profiles.py")
    else:
        with target.open("w", encoding="utf-8", newline="\n") as output:
            output.write(generated)


if __name__ == "__main__":
    main()
