option(XFILES_INTERACTIVE_TESTS "Run tests that change the display or play sound" OFF)

include(CTest)
if(BUILD_TESTING)
    add_executable(quick-menu-dialog-test tests/quick_menu_dialog.cpp src/settings.cpp
        src/localization/ui.cpp src/enhancements/ui/quick_menu_dialog.cpp
        src/enhancements/ui/settings.rc)
    target_include_directories(quick-menu-dialog-test PRIVATE src src/enhancements/ui)
    target_link_libraries(quick-menu-dialog-test PRIVATE user32)
    add_test(NAME quick-menu-dialog-settings COMMAND quick-menu-dialog-test)
    add_executable(quick-menu-navigation-test tests/quick_menu_navigation.cpp
        src/enhancements/screens.cpp src/enhancements/ui/quick_menu.cpp
        src/enhancements/ui/quick_menu_surface.cpp)
    target_include_directories(quick-menu-navigation-test PRIVATE src)
    target_link_libraries(quick-menu-navigation-test PRIVATE gdi32 user32 msimg32)
    add_test(NAME gameplay-quick-menu-navigation COMMAND quick-menu-navigation-test)
    add_executable(quick-menu-test tests/quick_menu.cpp src/enhancements/ui/quick_menu.cpp
        src/enhancements/ui/quick_menu_surface.cpp)
    target_include_directories(quick-menu-test PRIVATE src)
    target_link_libraries(quick-menu-test PRIVATE gdi32 user32 msimg32)
    add_test(NAME gameplay-quick-menu COMMAND quick-menu-test)
    add_executable(browser-session-test tests/browser_session.cpp src/saves/browser.cpp
        src/saves/browser_navigation.cpp src/enhancements/scene_overlay.cpp)
    target_include_directories(browser-session-test PRIVATE src)
    target_link_libraries(browser-session-test PRIVATE gdi32 user32)
    add_test(NAME save-browser-gameplay-session COMMAND browser-session-test)
    add_executable(transcript-history-test tests/transcript_history.cpp)
    target_include_directories(transcript-history-test PRIVATE src)
    add_test(NAME dialogue-transcript-history COMMAND transcript-history-test)
    add_executable(transcript-page-test tests/transcript_page.cpp src/transcript/page.cpp)
    target_include_directories(transcript-page-test PRIVATE src)
    target_link_libraries(transcript-page-test PRIVATE gdi32 user32)
    add_test(NAME dialogue-transcript-page COMMAND transcript-page-test)
    add_executable(transcript-capture-test tests/transcript_capture.cpp
        src/transcript/capture.cpp src/playback/captions.cpp src/playback/audio.cpp src/playback/output.cpp)
    target_include_directories(transcript-capture-test PRIVATE src)
    target_link_libraries(transcript-capture-test PRIVATE movie gdi32 user32 ole32 xaudio2 msimg32)
    add_test(NAME dialogue-transcript-capture COMMAND transcript-capture-test)
    add_executable(transcript-view-test tests/transcript_view.cpp src/transcript/view.cpp src/transcript/page.cpp)
    target_include_directories(transcript-view-test PRIVATE src)
    target_link_libraries(transcript-view-test PRIVATE gdi32 user32)
    add_test(NAME dialogue-transcript-input COMMAND transcript-view-test)
    add_executable(scene-overlay-test tests/scene_overlay.cpp src/enhancements/scene_overlay.cpp)
    target_include_directories(scene-overlay-test PRIVATE src)
    add_test(NAME gameplay-overlay-pause COMMAND scene-overlay-test)
    add_executable(menu-control-test tests/menu_control.cpp src/enhancements/menu_corner.cpp)
    target_include_directories(menu-control-test PRIVATE src)
    target_link_libraries(menu-control-test PRIVATE user32)
    add_test(NAME gameplay-menu-control COMMAND menu-control-test)
    add_executable(controller-delivery-test tests/controller_delivery.cpp)
    target_include_directories(controller-delivery-test PRIVATE src)
    target_link_libraries(controller-delivery-test PRIVATE user32)
    add_test(NAME controller-input-delivery COMMAND controller-delivery-test)
    add_executable(fast-forward-test tests/fast_forward.cpp src/settings.cpp)
    target_include_directories(fast-forward-test PRIVATE src)
    add_test(NAME movie-speed-release-barrier COMMAND fast-forward-test)
    add_executable(save-conversion-test tests/save_conversion.cpp)
    target_include_directories(save-conversion-test PRIVATE src)
    add_test(NAME save-conversion COMMAND save-conversion-test)
    add_test(NAME movie-grading-catalog COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/grading_catalog.py")
    add_executable(ui-colors-test tests/ui_colors.cpp)
    target_include_directories(ui-colors-test PRIVATE src)
    target_link_libraries(ui-colors-test PRIVATE movie-grading)
    add_test(NAME ui-artwork-cleanup COMMAND ui-colors-test)
    add_executable(menu-colors-test tests/menu_colors.cpp)
    target_include_directories(menu-colors-test PRIVATE src)
    add_test(NAME menu-credit-cleanup COMMAND menu-colors-test)
    add_executable(controller-state-test tests/controller_state.cpp)
    target_link_libraries(controller-state-test PRIVATE controller-input)
    add_test(NAME controller-device-state COMMAND controller-state-test)
    add_executable(controller-navigation-test tests/controller_navigation.cpp)
    target_link_libraries(controller-navigation-test PRIVATE controller-input)
    add_test(NAME controller-navigation-state COMMAND controller-navigation-test)
    add_executable(controller-click-test tests/controller_click.cpp)
    target_include_directories(controller-click-test PRIVATE src)
    add_test(NAME controller-click-dispatch COMMAND controller-click-test)
    add_executable(rumble-test tests/rumble.cpp)
    target_link_libraries(rumble-test PRIVATE controller-input)
    add_test(NAME controller-rumble-state COMMAND rumble-test)
    add_test(NAME controller-rumble-catalog COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/rumble_catalog.py")
    add_executable(ui-localization-test tests/localization.cpp src/localization/ui.cpp)
    target_include_directories(ui-localization-test PRIVATE src)
    add_test(NAME ui-language-selection COMMAND ui-localization-test)
    add_executable(welcome-test tests/welcome.cpp)
    target_link_libraries(welcome-test PRIVATE launcher-common)
    add_test(NAME first-launch-options COMMAND welcome-test)
    find_package(Python3 3.9 REQUIRED COMPONENTS Interpreter)
    add_test(NAME dvd-media-inventory COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/dvd_media_probe.py")
    add_test(NAME dvd-registration COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/dvd_registration.py")
    add_test(NAME fresh-ddraw-patches COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/ddraw_patch.py" "${ddraw_source}")
    add_test(NAME native-profile-schema COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/game_profiles.py")
    add_test(NAME native-ida-naming COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/game_ida.py")
    add_executable(game-strings-test tests/game_strings.cpp tests/game_strings.rc
        src/enhancements/game_strings.cpp)
    target_include_directories(game-strings-test PRIVATE src)
    add_test(NAME localized-resource-strings COMMAND game-strings-test)
    add_test(NAME release-package-checker COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/package_check.py")
    add_executable(installation-test tests/installation.cpp src/launcher/configuration.cpp
        src/setup/destination.cpp)
    target_include_directories(installation-test PRIVATE src)
    add_test(NAME installation-paths-and-settings COMMAND installation-test)
    add_executable(iso-files-test tests/iso_files.cpp src/setup/iso.cpp src/setup/disc_image.cpp src/setup/catalog.cpp
        "${CMAKE_BINARY_DIR}/generated/media-catalog.rc")
    target_link_libraries(iso-files-test PRIVATE launcher-common)
    add_test(NAME dvd-cd-iso-files COMMAND iso-files-test)
    add_executable(audio-edits-test tests/audio_edits.cpp)
    target_include_directories(audio-edits-test PRIVATE src)
    add_test(NAME audio-edit-rates COMMAND audio-edits-test)
    add_executable(report-test tests/report.cpp src/diagnostics/report.cpp src/diagnostics/log_file.cpp)
    target_include_directories(report-test PRIVATE src)
    add_test(NAME troubleshooting-report COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/report_zip.py" $<TARGET_FILE:report-test>)
    add_executable(log-file-test tests/log_file.cpp src/diagnostics/log_file.cpp)
    target_include_directories(log-file-test PRIVATE src)
    add_test(NAME bounded-logs COMMAND log-file-test)
    add_executable(image-codec-test tests/image_codec.cpp src/picture/pict.cpp)
    target_include_directories(image-codec-test PRIVATE src)
    add_test(NAME photo-save-codec COMMAND image-codec-test $<TARGET_FILE:quicktime>)

    add_executable(focus-test tests/focus.cpp src/enhancements/focus.cpp)
    target_include_directories(focus-test PRIVATE src)
    target_link_libraries(focus-test PRIVATE user32)
    add_test(NAME controller-focus COMMAND focus-test)

    add_executable(options-navigation-test tests/options_navigation.cpp
        src/enhancements/script_controls.cpp src/enhancements/focus.cpp)
    target_include_directories(options-navigation-test PRIVATE src)
    target_link_libraries(options-navigation-test PRIVATE user32)
    add_test(NAME options-navigation COMMAND options-navigation-test)

    add_executable(navigation-test tests/navigation.cpp src/enhancements/inventory.cpp)
    target_include_directories(navigation-test PRIVATE src)
    target_link_libraries(navigation-test PRIVATE user32)
    add_test(NAME inventory-navigation COMMAND navigation-test)

    add_executable(native-gun-test tests/native_gun.cpp src/enhancements/gun.cpp)
    target_include_directories(native-gun-test PRIVATE src)
    target_link_libraries(native-gun-test PRIVATE user32)
    add_test(NAME native-gun-equip COMMAND native-gun-test)

    add_executable(session-test tests/session.cpp src/launcher/session.cpp
        src/launcher/preferences.cpp src/preferences/store.cpp)
    target_include_directories(session-test PRIVATE src)
    target_link_libraries(session-test PRIVATE advapi32)
    add_test(NAME launcher-session COMMAND session-test)

    add_executable(abi-test tests/abi.cpp)
    add_test(NAME dispatcher-abi COMMAND abi-test $<TARGET_FILE:quicktime>)

    add_executable(movie-test tests/movie.cpp)
    target_link_libraries(movie-test PRIVATE movie)
    add_test(NAME movie-reader COMMAND movie-test)

    add_executable(mpeg-test tests/mpeg.cpp)
    target_link_libraries(mpeg-test PRIVATE movie psapi)
    add_test(NAME dvd-mpeg-stream COMMAND mpeg-test "${PROJECT_SOURCE_DIR}/tests/fixtures")
    add_executable(mpeg-filter-test tests/mpeg_filter.cpp)
    target_link_libraries(mpeg-filter-test PRIVATE movie)
    add_test(NAME dvd-bwdif COMMAND mpeg-filter-test "${PROJECT_SOURCE_DIR}/tests/fixtures")
    add_executable(dvd-player-test tests/dvd_player.cpp)
    target_link_libraries(dvd-player-test PRIVATE dvd-player)
    add_test(NAME dvd-presentation COMMAND dvd-player-test "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg")
    add_test(NAME dvd-bwdif-presentation COMMAND dvd-player-test "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg" --bwdif)
    add_executable(dvd-caption-test tests/dvd_captions.cpp)
    target_link_libraries(dvd-caption-test PRIVATE dvd-player)
    add_test(NAME dvd-caption-mapping COMMAND dvd-caption-test)
    add_executable(dvd-clock-test tests/dvd_clock.cpp)
    target_include_directories(dvd-clock-test PRIVATE src)
    add_test(NAME dvd-playback-clock COMMAND dvd-clock-test)
    add_executable(dvd-focus-test tests/dvd_focus.cpp)
    target_include_directories(dvd-focus-test PRIVATE src)
    target_link_libraries(dvd-focus-test PRIVATE user32 comctl32)
    add_test(NAME dvd-focus-barrier COMMAND dvd-focus-test)
    add_executable(dvd-numeric-test tests/dvd_numeric.cpp)
    target_include_directories(dvd-numeric-test PRIVATE src)
    target_link_libraries(dvd-numeric-test PRIVATE user32)
    add_library(dvd-test-driver SHARED src/dvd/adapter.cpp tests/dvd_output_fake.cpp src/settings.cpp src/dvd/adapter.def)
    target_link_libraries(dvd-test-driver PRIVATE dvd-player user32 comctl32)
    add_executable(dvd-abi-test tests/dvd_abi.cpp)
    target_link_libraries(dvd-abi-test PRIVATE user32)
    add_custom_command(TARGET dvd-abi-test POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:dvd-abi-test>/vob"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg"
            "$<TARGET_FILE_DIR:dvd-abi-test>/vob/dvd-hook-fixture.vob")
    add_test(NAME dvd-native-abi COMMAND dvd-abi-test $<TARGET_FILE:dvd-test-driver> "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg")
    add_test(NAME dvd-disabled-fallback COMMAND "${Python3_EXECUTABLE}"
        "${PROJECT_SOURCE_DIR}/tests/dvd_disabled.py" $<TARGET_FILE:dvd-abi-test>
        $<TARGET_FILE:dvd-test-driver> "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg")
    add_executable(dvd-output-test tests/dvd_output.cpp src/dvd/output.cpp)
    target_link_libraries(dvd-output-test PRIVATE dvd-player user32 gdi32 msimg32 ole32 xaudio2)
    add_test(NAME dvd-output-composition COMMAND dvd-output-test)
    if(XFILES_INTERACTIVE_TESTS)
        add_test(NAME dvd-native-output COMMAND dvd-abi-test $<TARGET_FILE:dvd-mpeg> "${PROJECT_SOURCE_DIR}/tests/fixtures/dvd-stream.mpg" --interactive)
        add_test(NAME dvd-audio-speed COMMAND dvd-output-test --audio-speed)
        set_tests_properties(dvd-audio-speed PROPERTIES LABELS "audio-hardware")
    endif()
    add_executable(codec-staging-test tests/codec_staging.cpp)
    target_link_libraries(codec-staging-test PRIVATE launcher-common)
    add_dependencies(codec-staging-test quicktime xfiles-patch)
    add_test(NAME codec-staging-files COMMAND codec-staging-test)

    add_executable(devtools-test "${CMAKE_BINARY_DIR}/generated/clip-labels.rc" tests/devtools.cpp src/devtools/caption_index.cpp src/devtools/clip_key.cpp src/devtools/artwork.cpp src/devtools/variables.cpp src/devtools/preview.cpp src/devtools/clip_defaults.cpp src/playback/audio.cpp)
    target_include_directories(devtools-test PRIVATE src)
    target_link_libraries(devtools-test PRIVATE movie)
    add_test(NAME independent-preview COMMAND devtools-test)
    add_executable(subtitles-test tests/subtitles.cpp)
    add_executable(clip-notes-test tests/clip_notes.cpp)
    target_link_libraries(clip-notes-test PRIVATE clip-notes)
    add_test(NAME clip-notes COMMAND clip-notes-test)
    add_executable(clip-index-test tests/clip_index.cpp)
    target_link_libraries(clip-index-test PRIVATE clip-index)
    add_test(NAME clip-index COMMAND clip-index-test)
    target_link_libraries(subtitles-test PRIVATE movie)
    add_test(NAME subtitle-export-overrides COMMAND "${Python3_EXECUTABLE}"
        "${PROJECT_SOURCE_DIR}/tests/subtitle_zip.py" $<TARGET_FILE:subtitles-test>)

    add_executable(save-storage-test tests/save_storage.cpp src/saves/storage.cpp src/saves/paths.cpp src/saves/catalog.cpp)
    target_include_directories(save-storage-test PRIVATE src)
    add_test(NAME save-storage COMMAND save-storage-test)
    add_executable(save-compatibility-test tests/save_compatibility.cpp)
    target_include_directories(save-compatibility-test PRIVATE src)
    add_test(NAME save-compatibility COMMAND save-compatibility-test)
    add_executable(save-slots-test tests/save_slots.cpp src/saves/slots.cpp src/saves/catalog.cpp)
    target_include_directories(save-slots-test PRIVATE src)
    add_test(NAME save-slots COMMAND save-slots-test)
    add_executable(save-browser-test tests/save_browser.cpp src/saves/browser_paint.cpp src/saves/browser_navigation.cpp src/saves/browser_text.cpp src/saves/preview.cpp src/saves/artwork.cpp src/saves/slots.cpp src/saves/catalog.cpp src/picture/pict.cpp)
    target_include_directories(save-browser-test PRIVATE src)
    target_link_libraries(save-browser-test PRIVATE movie gdi32 user32)
    add_test(NAME save-browser COMMAND save-browser-test)
    add_executable(native-render-test tests/native_render.cpp src/game/render/caption_surface.cpp)
    target_include_directories(native-render-test PRIVATE src)
    target_link_libraries(native-render-test PRIVATE gdi32 user32)
    add_test(NAME native-caption-composition COMMAND native-render-test)
    add_executable(canvas-presentation-test tests/canvas_presentation.cpp src/game/render/native_render.cpp src/game/render/gdi_hooks.cpp src/game/render/caption_surface.cpp src/platform/imports.cpp)
    target_include_directories(canvas-presentation-test PRIVATE src)
    target_link_libraries(canvas-presentation-test PRIVATE gdi32 user32)
    add_test(NAME canvas-presentation COMMAND canvas-presentation-test)

    add_executable(save-hooks-test tests/save_hooks.cpp)
    target_include_directories(save-hooks-test PRIVATE src)
    target_link_libraries(save-hooks-test PRIVATE comdlg32)
    add_test(NAME native-save-files COMMAND save-hooks-test $<TARGET_FILE:quicktime>)

    add_executable(audio-test tests/audio.cpp)
    target_link_libraries(audio-test PRIVATE movie)
    add_test(NAME ima4-audio COMMAND audio-test)

    add_executable(compressed-audio-test tests/compressed_audio.cpp)
    target_link_libraries(compressed-audio-test PRIVATE movie)
    add_test(NAME compressed-audio COMMAND compressed-audio-test)

    add_executable(playback-test tests/playback.cpp src/settings.cpp)
    target_include_directories(playback-test PRIVATE src)
    add_test(NAME movie-playback COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/run_logged.py"
        "${CMAKE_BINARY_DIR}/test-logs/movie-playback.log" $<TARGET_FILE:playback-test> $<TARGET_FILE:quicktime> --no-audio)
    foreach(mode below background)
        add_test(NAME movie-captions-${mode} COMMAND "${Python3_EXECUTABLE}"
            "${PROJECT_SOURCE_DIR}/tests/run_caption_variant.py"
            $<TARGET_FILE:playback-test> $<TARGET_FILE:quicktime> ${mode})
    endforeach()
    if(XFILES_INTERACTIVE_TESTS)
    add_test(NAME movie-playback-audio COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tests/run_logged.py"
        "${CMAKE_BINARY_DIR}/test-logs/movie-playback-audio.log" $<TARGET_FILE:playback-test> $<TARGET_FILE:quicktime>)
    set_tests_properties(movie-playback-audio PROPERTIES LABELS audio-hardware)
    endif()

    add_executable(video-test tests/video.cpp)
    target_link_libraries(video-test PRIVATE movie)
    add_test(NAME video-codecs COMMAND video-test)

    add_executable(media-files-test tests/media_files.cpp)
    target_include_directories(media-files-test PRIVATE src)
    add_test(NAME local-media COMMAND media-files-test $<TARGET_FILE:quicktime>)

    add_executable(world-test tests/world.cpp)
    target_include_directories(world-test PRIVATE src)
    target_link_libraries(world-test PRIVATE gdi32 user32)
    add_test(NAME quickdraw-world COMMAND world-test $<TARGET_FILE:quicktime>)

    add_executable(picture-test tests/picture.cpp tests/picture_indexed.cpp src/picture/pict.cpp)
    target_include_directories(picture-test PRIVATE src)
    add_test(NAME quickdraw-picture COMMAND picture-test $<TARGET_FILE:quicktime>)

    add_executable(region-test tests/regions.cpp)
    target_include_directories(region-test PRIVATE src)
    target_link_libraries(region-test PRIVATE gdi32 user32)
    add_test(NAME quickdraw-regions COMMAND region-test $<TARGET_FILE:quicktime>)

    add_executable(memory-test tests/memory.cpp)
    target_include_directories(memory-test PRIVATE src)
    add_test(NAME memory-handles COMMAND memory-test $<TARGET_FILE:quicktime>)

    add_executable(preferences-test tests/preferences.cpp src/preferences/store.cpp)
    target_include_directories(preferences-test PRIVATE src)
    target_link_libraries(preferences-test PRIVATE advapi32)
    add_test(NAME portable-preferences COMMAND preferences-test $<TARGET_FILE:quicktime>)

    add_executable(display-test
        src/diagnostics/log_file.cpp
        tests/display.cpp
        src/graphics.cpp
        src/log.cpp
        src/identity.cpp
        src/platform/desktop.cpp
    )
    target_include_directories(display-test PRIVATE src "${CMAKE_BINARY_DIR}/generated")
    target_link_libraries(display-test PRIVATE bcrypt dxguid user32 gdi32 controller-input)
    add_dependencies(display-test display-files)
    if(XFILES_INTERACTIVE_TESTS)
    add_test(NAME display-compatibility
        COMMAND display-test "$<TARGET_FILE_DIR:xfiles-patch>/ddraw.dll")
    set_tests_properties(display-compatibility PROPERTIES TIMEOUT 30 RUN_SERIAL TRUE)
    endif()
endif()

if(BUILD_TESTING)
    add_executable(setup-test tests/setup.cpp tests/setup_iso.cpp src/setup/shortcuts.cpp src/setup/media.cpp src/setup/destination.cpp src/setup/iso.cpp src/setup/disc_image.cpp src/setup/catalog.cpp
        "${CMAKE_BINARY_DIR}/generated/media-catalog.rc")
    target_link_libraries(setup-test PRIVATE launcher-common ole32 uuid shell32)
    add_dependencies(setup-test xfiles-patch)
    add_test(NAME setup-validation COMMAND setup-test)
endif()
